### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/coffeescript#171]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- `docs/ABOUT.md`
- `docs/INSTALLATION.md`
- `docs/LEARNING.md`
- `docs/RESOURCES.md`
- `docs/TESTS.md`
- `exercises/shared/.docs/help.md`
- `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total...........26
✅ Successful......24
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........2

Errors in ./docs/RESOURCES.md
<span style="color:#ff5555">✗ http://x.exercism.io/v3/tracks/coffeescript/docs/img/SolutionExplorer.png (HTTP status client error (404 Not Found) for url (https://x.exercism.io/v3/tracks/coffeescript/docs/img/SolutionExplorer.png))</span>
<span style="color:#ff5555">✗ http://x.exercism.io/v3/tracks/coffeescript/docs/img/AddFiles.png (HTTP status client error (404 Not Found) for url (https://x.exercism.io/v3/tracks/coffeescript/docs/img/AddFiles.png))</span>

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by safwansamsudeen** [comment]
@ErikSchierboom Hey, can I take this up? I'm planning to work on the CoffeeScript track over the coming weeks, if that's possible.

**Comment by ErikSchierboom** [comment]
Yeah sure!

**Comment by safwansamsudeen** [comment]
@ErikSchierboom here's #226.
