### ISSUE TITLE
Exercises to port

### ISSUE THREAD

**Issue by BNAndras** [exercism/coffeescript#236]
Here are some exercises I'd like to port over the next few weeks.

- [ ] Flatten Array

Done
- [x] Armstrong Numbers
- [x] Binary Search
- [x] Collatz Conjecture
- [x] Darts
- [x] Eliud's Eggs
- [x] ETL
- [x] Grains
- [x] Hamming
- [x] High Scores
- [x] Isogram
- [x] Leap
- [x] Pangram
- [x] Protein Translation
- [x] Raindrops
- [x] Resistor Color
- [x] Resistor Color Duo
- [x] Robot Simulator
- [x] Roman Numerals
- [x] Space Age
- [x] Square Root
- [x] Strain

**Comment by BNAndras** [comment]
@ErikSchierboom, I have some new exercise PRs for your review. Once these are merged in, I'll rebase #237 and sort the practice exercises by displayed difficulty and then name.

**Comment by ErikSchierboom** [comment]
@BNAndras I've reviewed them
