### ISSUE TITLE
How do I run the test file?

### ISSUE THREAD

**Issue by Carpetsmoker** [exercism/coffeescript#39]
It's not at all obvious to me how I should run the `bob_test.spec.coffee` file.

I have only used CoffeeScript in the browser. I assume I have to run this with node.js somehow?

Also, the file looks like:

```
Bob = require "./bob"
describe "Bob", ->
bob = new Bob()
it "stating something", ->
    result = bob.hey "Tom-ay-to, tom-aaaah-to."
    expect(result).toEqual "Whatever."
```

So I think I need to install some sort package to run the tests? AFAIK CoffeeScript doesn't include those by default?

Thanks ;-)

**Comment by kytrinyx** [comment]
It's documented in the help site:
http://help.exercism.io/getting-started-with-coffeescript.html

We should probably add this to the READMEs.

If you have a moment, do you want to add a `SETUP.md` at the root of the https://github.com/exercism/xcoffeescript repo that explains how to run the tests?

The api checks if there is a SETUP.md file, and if it is, it sticks the contents into the README for each of the problems that get delivered via the `exercism fetch` command.
