### ISSUE TITLE
Need ABOUT.md and LEARNING.md

### ISSUE THREAD

**Issue by outkaj** [exercism/coffeescript#51]
A short description about CoffeeScript, as well as information about resources for learning the language, are missing from [the CoffeeScript track of the website](http://exercism.io/languages/coffeescript). This can be fixed by adding an ABOUT.md and LEARNING.md to docs/ with relevant information. The LEARNING.md could just link to the Useful CoffeeScript Resources page since the information is similar.

**Comment by kytrinyx** [comment]
`LEARNING` is specifically about learning the language from scratch. `RESOURCES` should be things like references and linters--helpful while developing, but not necessarily about learning.

**Comment by outkaj** [comment]
Thanks for the correction!

**Comment by safwansamsudeen** [comment]
@ErikSchierboom this can be closed.
