### ISSUE TITLE
incorrect installation instructions

### ISSUE THREAD

**Issue by metalim** [exercism/coffeescript#64]
Instruction says:
`$ npm install jasmine-node coffee -g
`
`coffee` package on npmjs has **nothing** to do with coffee-script. Just remove it from instructions, as `jasmine-node` has `coffee-script` in it's dependencies.

**Comment by kytrinyx** [comment]
That's a great catch, thank you.

The document in question is [docs/INSTALLATION.md](https://github.com/exercism/xcoffeescript/blob/master/docs/INSTALLATION.md) in this repository.

**Comment by aimorris** [comment]
[commit](https://github.com/exercism/coffeescript/commit/a42482606943456956d0bbe5b38686a08973e8e1)
